# Generated by Django 5.0.7 on 2024-07-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
